# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c33305ab7e1cef2911e071c8abb7144d21e3150de6cb69b9a00256eb24781b8fb4677365f674343ddb3d549e64a19da702dbcd25ede957661faa12c31e56f2ba

test:
  secret_key_base: 35088ff306750b316d0f92f94bdc6f3432cfb13b08ea099e65d3bbe5b81ec1e9177574f697d798525d8966c9994d554fce001e0cf4b05aa7acd21e8c46d78506

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
